
public class ExceptionRunner {

	void getData()
	{
		throw new Exception("1st exception");
	}
	
}
